In [2]:

from mysql import connector
from getpass import getpass
import pandas as pd
import PySimpleGUI as sg

In [3]:
mysql_con = connector.connect(host="localhost", user = "root", password = "Root@123")
print("Mysql Connection: ", mysql_con)

Mysql Connection:  <mysql.connector.connection_cext.CMySQLConnection object at 0x000001A6941005B0>

In [4]:
def sakila_db(query):
    db = "use sakila;"
    with connector.connect(
        host = "localhost", 
        user = "root", 
        password = "Root@123") as mysqlcon:
        print(mysqlcon)
        cur = mysqlcon.cursor()
        print(cur)
        cur.execute(db)
        cur.execute(query)
        df = pd.DataFrame(cur.fetchall())
        return df

In [5]:
  def sakila():  
    
    sg.theme("DarkPurple4")
    title="Queries of Actor Table"
    
    layout=[[sg.Text("Extract the names and addresses of staff", size=(30,2)), 
                sg.Button("open", key="one",size=(10,2))], 
            [sg.Text("Display the total sales generated by each employee", size=(30,2)), 
                sg.Button("open", key="two",size=(10,2))], 
            [sg.Text("Display the total sales generated by each employee for the month of July 2005", size=(30,2)), 
                 sg.Button("open", key="three",size=(10,2))], 
            [sg.Text("display each film and the number of actors in it", size=(30,2)), 
                 sg.Button("open", key="four",size=(10,2))], 
            [sg.Text(" get the names and email address of all customers in Canada", size=(30,2)), 
                sg.Button("open", key="five",size=(10,2))], 
            [sg.Text(" display all documentary films", size=(30,2)), 
                 sg.Button("open", key="six",size=(10,2))]]
    
      
    
    window=sg.Window(title,layout)
    
    while True:
        event,value=window.read()
                
        if event == "one":
            query = "select staff.first_name, staff.last_name, address.address from staff inner join address on address.address_id = staff.address_id;"
            df = sakila_db(query)
    
        if event == "two":
            query = "select concat(staff.first_name, ' ', staff.last_name) Staff, sum(payment.amount) from staff inner join payment on staff.staff_id = payment.staff_id group by payment.staff_id;"
            df = sakila_db(query)
        
        if event == "three":
            query = "select concat(staff.first_name, ' ', staff.last_name) Staff, sum(payment.amount) from staff inner join payment on staff.staff_id = payment.staff_id where payment.payment_date like '%-07-%' group by payment.staff_id ;"
            df = sakila_db(query)
        
        if event == "four":
            query = "select film.title, count(film_actor.actor_id) from film inner join film_actor on film.film_id = film_actor.film_id group by film.title;"
            df = sakila_db(query)
        
        if event == "five":
            query = "select customer.first_name, customer.last_name, customer.email from customer inner join address on customer.address_id = address.address_id inner join city on city.city_id = address.city_id inner join country on country.country_id = city.country_id where country.country = 'Canada';"
            df = sakila_db(query)
         
        if event == "six":
            query = "select title from film inner join film_category on film.film_id = film_category.film_id inner join category on film_category.category_id = category.category_id where category.name = 'Documentary';"
            df = sakila_db(query)
        
       
                   
            window.close()
            
            
        if  event == sg.WIN_CLOSED:
            break
    window.close()

In [6]:
def real_time():
    layout = [ 
    [sg.Text("Enter to Query from 'sakila' Database")], 
    [sg.Text('Enter the Database and Query', size =(22, 1)), 
     sg.InputText("sakila"), sg.Text('Query', size =(5, 1)), sg.InputText("Query")], 
    [sg.Text('', size =(95, 1)), sg.Submit(), sg.Cancel()]] 
  
    window = sg.Window('User Input MYSQL Query', layout) 
    event, values = window.read() 
    window.close() 
  
    db = "use" + " " + values[0] + ";"
    query = values[1] + ";"    
    with connector.connect(
        host = "localhost", 
        user = "root", 
        password = "Root@123") as mysqlcon:
        print(mysqlcon)
        cur = mysqlcon.cursor()
        print(cur)
        cur.execute(db)
        cur.execute(query)
        df = pd.DataFrame(cur.fetchall())
        return df

In [7]:
title="SQL QUERY INTERFACE "
sg.theme("DarkPurple4")
title="SQL GUI"    
main_line = [sg.Text(size=(10,1)), sg.Text("Click the Buttons")]

layout=[[sg.Text("Click the Buttons")],
        [sg.Button("Sakila Database", key="sakila", size=(20,3)),sg.Button("Own Database", key="own", size=(20,3))]] 


window=sg.Window(title,layout)
    
while True:
    event,value=window.read()   

    if event == "sakila":
        sakila()
        
    if event == "own":
        df=real_time()
        df1 = pd.DataFrame(df)
        
    
 
    if event == sg.WIN_CLOSED:
        break
window.close()

In [8]:
df1

NameError: name 'df1' is not defined

In [ ]:
df2 = pd.DataFrame(df2)
df2.head()

In [ ]:
df